### ISSUE TITLE
Add an executable file for download?

### ISSUE THREAD

**Issue by guemax** [mkroening/altarplanner#1]
Hi,
I'm very interested in trying out your _altarplanner_. Unfortunately I have no idea how to build it with Java (or even download Java).
It would be great if you could provide an executable (for Windows), so others can try out your program and improve it.

Thanks in advance!

P.S. It's not a problem if it's only a development version, I'm just curious about the look of your program and how you can interact with it, creating new plans and so on; it does not need to be ready for everyday planning.

**Comment by mkroening** [comment]
Thanks for your interest!

I tagged [`v0.1.0`](https://github.com/mkroening/altarplanner/releases/tag/v0.1.0) and uploaded my last build from November. Just execute `bin/altarplanner-app.bat`. Let me know if it works for you.

Note that this project is not documented and might not be intuitive to use. While we use AltarPlanner ourselves very successfully, I consider the project dormant. I started a complete rewrite once, but never finished it. I am considering rewriting it using different technologies for the front-end (not JavaFX). That would be a separate project though and it will be a few months until I have time to attempt such a thing. So no use waiting for that, I think.

So please try out AltarPlanner. If you have questions or need an overview of working with AltarPlanner feel free to open a new issue.

**Comment by guemax** [comment]
Thank you for your quick reply!

It was a bit tricky to get it running (I had to install Java), but I finally was able to try it out. Am very interested in your new version of it, even though the front-end already looks very good.
